server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;
  charset utf-8;
  absolute_redirect off;

  gzip on;
  gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss image/svg+xml;

  location ~ ^/(privacy|terms|support)/$ {
    return 301 /$1;
  }

  location / {
    try_files $uri $uri.html /index.html;
  }
}
