export const QK = {
  me: () => ["me"] as const,
  schools: (q: Record<string, unknown>) => ["schools", q] as const,
  departments: (schoolId?: string, q?: string) => ["departments", schoolId, q] as const,
  semesters: () => ["semesters"] as const,
  templates: (q: { schoolId?: string; departmentId?: string; q?: string }) => ["templates", q] as const,
  userTimetables: () => ["user-timetables"] as const,
  userTimetable: (id: string) => ["user-timetables", id] as const,
  today: (date?: string) => ["today", date ?? "current"] as const,
  dayDetail: (date?: string | null) => ["day", date ?? "none"] as const,
  stats: (semesterId?: string | null) => ["stats", semesterId ?? "current"] as const,
  courseSuspensions: (courseId: string) => ["courses", courseId, "suspensions"] as const,
  timetableSuspensions: (range: { from?: string; to?: string } = {}) => ["timetable-suspensions", range] as const,
  personalEvents: (range: { from?: string; to?: string } = {}) => ["personal-events", range] as const,
  semesterOverview: (semesterId?: string | null) => ["semesters", semesterId ?? "any", "overview"] as const,
  rules: (scope: { schoolId?: string | null; departmentId?: string | null }) => ["attendance-rules", scope] as const,
  friendships: (q: { status?: string; direction?: string } = {}) => ["friendships", q] as const,
  friendshipsPendingCount: () => ["friendships", "pending-count"] as const,
  usersSearch: (handle: string) => ["users", "search", handle] as const,
  rooms: () => ["rooms"] as const,
  room: (id: string) => ["rooms", id] as const,
  roomMembers: (id: string) => ["rooms", id, "members"] as const,
  roomWeek: (id: string, weekStart: string) => ["rooms", id, "week", weekStart] as const,
  roomEvents: (id: string, range: { from?: string; to?: string }) => ["rooms", id, "events", range] as const,
  icsImports: (id: string) => ["rooms", id, "ics-imports"] as const,
  icsImportPreview: (id: string, importId: string) => ["rooms", id, "ics-imports", importId, "preview"] as const,
  icsTitleRules: () => ["me", "ics-title-rules"] as const,
  googleConnection: () => ["me", "google-calendar", "connection"] as const,
  googleCalendars: () => ["me", "google-calendar", "calendars"] as const,
  googleSyncs: (roomId: string) => ["rooms", roomId, "google-calendar-syncs"] as const,
} as const;
