export const QK = {
  me: () => ["me"] as const,
  schools: (q: Record<string, unknown>) => ["schools", q] as const,
  departments: (schoolId?: string, q?: string) => ["departments", schoolId, q] as const,
  semesters: () => ["semesters"] as const,
  templates: (q: { schoolId?: string; departmentId?: string; q?: string }) => ["templates", q] as const,
  userTimetables: () => ["user-timetables"] as const,
  userTimetable: (id: string) => ["user-timetables", id] as const,
  today: (date?: string) => ["today", date ?? "current"] as const,
  stats: (semesterId?: string | null) => ["stats", semesterId ?? "current"] as const,
  rules: (scope: { schoolId?: string | null; departmentId?: string | null }) => ["attendance-rules", scope] as const,
  friendships: (q: { status?: string; direction?: string } = {}) => ["friendships", q] as const,
  friendshipsPendingCount: () => ["friendships", "pending-count"] as const,
  usersSearch: (handle: string) => ["users", "search", handle] as const,
  rooms: () => ["rooms"] as const,
  room: (id: string) => ["rooms", id] as const,
  roomMembers: (id: string) => ["rooms", id, "members"] as const,
  roomWeek: (id: string, weekStart: string) => ["rooms", id, "week", weekStart] as const,
  roomEvents: (id: string, range: { from?: string; to?: string }) => ["rooms", id, "events", range] as const,
} as const;
